run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.24"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    # Ignore fmt.Fprintf-style functions in specific cases
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Fprint

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - whyNoLint
      - unnamedResult

  gocyclo:
    min-complexity: 15

  govet:
    enable-all: true
    disable:
      - shadow # Will fix separately

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: true
    require-explanation: true
    require-specific: true

  revive:
    min-confidence: 0.8

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam

  disable:
    - exhaustivestruct
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golint
    - interfacer
    - maligned
    - scopelint

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some lints from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic
    
    # Ignore complexity in test files
    - path: _test\.go
      linters:
        - gocyclo
    
    # Ignore magic numbers in tests
    - path: _test\.go
      text: "mnd:"

  max-issues-per-linter: 0
  max-same-issues: 0