// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: pkg/plugin/sdk/v1/plugin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamMessage_Type int32

const (
	StreamMessage_STDIN  StreamMessage_Type = 0
	StreamMessage_STDOUT StreamMessage_Type = 1
	StreamMessage_STDERR StreamMessage_Type = 2
	StreamMessage_RESIZE StreamMessage_Type = 3
	StreamMessage_SIGNAL StreamMessage_Type = 4
	StreamMessage_EXIT   StreamMessage_Type = 5
	StreamMessage_ERROR  StreamMessage_Type = 6
	StreamMessage_PING   StreamMessage_Type = 7
	StreamMessage_PONG   StreamMessage_Type = 8
)

// Enum value maps for StreamMessage_Type.
var (
	StreamMessage_Type_name = map[int32]string{
		0: "STDIN",
		1: "STDOUT",
		2: "STDERR",
		3: "RESIZE",
		4: "SIGNAL",
		5: "EXIT",
		6: "ERROR",
		7: "PING",
		8: "PONG",
	}
	StreamMessage_Type_value = map[string]int32{
		"STDIN":  0,
		"STDOUT": 1,
		"STDERR": 2,
		"RESIZE": 3,
		"SIGNAL": 4,
		"EXIT":   5,
		"ERROR":  6,
		"PING":   7,
		"PONG":   8,
	}
)

func (x StreamMessage_Type) Enum() *StreamMessage_Type {
	p := new(StreamMessage_Type)
	*p = x
	return p
}

func (x StreamMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_plugin_sdk_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (StreamMessage_Type) Type() protoreflect.EnumType {
	return &file_pkg_plugin_sdk_v1_plugin_proto_enumTypes[0]
}

func (x StreamMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamMessage_Type.Descriptor instead.
func (StreamMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{12, 0}
}

// Empty message for RPC calls with no parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MinSdk        string                 `protobuf:"bytes,5,opt,name=min_sdk,json=minSdk,proto3" json:"min_sdk,omitempty"`
	BuildTimeUnix int64                  `protobuf:"varint,6,opt,name=build_time_unix,json=buildTimeUnix,proto3" json:"build_time_unix,omitempty"` // Unix timestamp
	Homepage      string                 `protobuf:"bytes,7,opt,name=homepage,proto3" json:"homepage,omitempty"`
	License       string                 `protobuf:"bytes,8,opt,name=license,proto3" json:"license,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"` // Tags for categorization (e.g., "database", "testing")
	Extra         map[string]string      `protobuf:"bytes,10,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aliases       []string               `protobuf:"bytes,11,rep,name=aliases,proto3" json:"aliases,omitempty"`           // Plugin name aliases (e.g., "db" for "database")
	Namespaced    bool                   `protobuf:"varint,12,opt,name=namespaced,proto3" json:"namespaced,omitempty"`    // If true, commands are namespaced under plugin name (default: true)
	Dependencies  []*PluginDependency    `protobuf:"bytes,13,rep,name=dependencies,proto3" json:"dependencies,omitempty"` // Plugin dependencies for load order resolution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetadata.ProtoReflect.Descriptor instead.
func (*PluginMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginMetadata) GetMinSdk() string {
	if x != nil {
		return x.MinSdk
	}
	return ""
}

func (x *PluginMetadata) GetBuildTimeUnix() int64 {
	if x != nil {
		return x.BuildTimeUnix
	}
	return 0
}

func (x *PluginMetadata) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *PluginMetadata) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *PluginMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PluginMetadata) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *PluginMetadata) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *PluginMetadata) GetNamespaced() bool {
	if x != nil {
		return x.Namespaced
	}
	return false
}

func (x *PluginMetadata) GetDependencies() []*PluginDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type PluginDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`          // Plugin name (e.g., "docker")
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`    // Semver constraint (e.g., "^1.0.0")
	Optional      bool                   `protobuf:"varint,3,opt,name=optional,proto3" json:"optional,omitempty"` // If true, dependency is optional (loading continues if missing/incompatible)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginDependency) Reset() {
	*x = PluginDependency{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDependency) ProtoMessage() {}

func (x *PluginDependency) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDependency.ProtoReflect.Descriptor instead.
func (*PluginDependency) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginDependency) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

type CommandInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Aliases       []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Interactive   bool                   `protobuf:"varint,5,opt,name=interactive,proto3" json:"interactive,omitempty"`
	Hidden        bool                   `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	RequiresTty   bool                   `protobuf:"varint,7,opt,name=requires_tty,json=requiresTty,proto3" json:"requires_tty,omitempty"`
	RequiresAuth  bool                   `protobuf:"varint,8,opt,name=requires_auth,json=requiresAuth,proto3" json:"requires_auth,omitempty"`
	Visibility    string                 `protobuf:"bytes,9,opt,name=visibility,proto3" json:"visibility,omitempty"` // Context visibility: "always", "project-only", "worktree-only", "root-only", "non-root"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInfo) Reset() {
	*x = CommandInfo{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfo) ProtoMessage() {}

func (x *CommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfo.ProtoReflect.Descriptor instead.
func (*CommandInfo) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CommandInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CommandInfo) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *CommandInfo) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *CommandInfo) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *CommandInfo) GetRequiresTty() bool {
	if x != nil {
		return x.RequiresTty
	}
	return false
}

func (x *CommandInfo) GetRequiresAuth() bool {
	if x != nil {
		return x.RequiresAuth
	}
	return false
}

func (x *CommandInfo) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type CommandList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandInfo         `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandList) Reset() {
	*x = CommandList{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandList) ProtoMessage() {}

func (x *CommandList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandList.ProtoReflect.Descriptor instead.
func (*CommandList) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *CommandList) GetCommands() []*CommandInfo {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Flags         map[string]string      `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkDir       string                 `protobuf:"bytes,5,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Stdin         []byte                 `protobuf:"bytes,6,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ExecuteRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type ExecuteResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode            int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout              []byte                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr              []byte                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error               string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	RequiresInteractive bool                   `protobuf:"varint,6,opt,name=requires_interactive,json=requiresInteractive,proto3" json:"requires_interactive,omitempty"`
	Extra               map[string]string      `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecuteResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetRequiresInteractive() bool {
	if x != nil {
		return x.RequiresInteractive
	}
	return false
}

func (x *ExecuteResponse) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Capabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequiresDocker      bool                   `protobuf:"varint,1,opt,name=requires_docker,json=requiresDocker,proto3" json:"requires_docker,omitempty"`
	RequiresNetwork     bool                   `protobuf:"varint,2,opt,name=requires_network,json=requiresNetwork,proto3" json:"requires_network,omitempty"`
	RequiresFilesystem  bool                   `protobuf:"varint,3,opt,name=requires_filesystem,json=requiresFilesystem,proto3" json:"requires_filesystem,omitempty"`
	RequiresInteractive bool                   `protobuf:"varint,4,opt,name=requires_interactive,json=requiresInteractive,proto3" json:"requires_interactive,omitempty"`
	RequiredCommands    []string               `protobuf:"bytes,5,rep,name=required_commands,json=requiredCommands,proto3" json:"required_commands,omitempty"`
	RequiredPaths       []string               `protobuf:"bytes,6,rep,name=required_paths,json=requiredPaths,proto3" json:"required_paths,omitempty"`
	RequiredEnvVars     []string               `protobuf:"bytes,7,rep,name=required_env_vars,json=requiredEnvVars,proto3" json:"required_env_vars,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Capabilities) GetRequiresDocker() bool {
	if x != nil {
		return x.RequiresDocker
	}
	return false
}

func (x *Capabilities) GetRequiresNetwork() bool {
	if x != nil {
		return x.RequiresNetwork
	}
	return false
}

func (x *Capabilities) GetRequiresFilesystem() bool {
	if x != nil {
		return x.RequiresFilesystem
	}
	return false
}

func (x *Capabilities) GetRequiresInteractive() bool {
	if x != nil {
		return x.RequiresInteractive
	}
	return false
}

func (x *Capabilities) GetRequiredCommands() []string {
	if x != nil {
		return x.RequiredCommands
	}
	return nil
}

func (x *Capabilities) GetRequiredPaths() []string {
	if x != nil {
		return x.RequiredPaths
	}
	return nil
}

func (x *Capabilities) GetRequiredEnvVars() []string {
	if x != nil {
		return x.RequiredEnvVars
	}
	return nil
}

// CustomCategory allows plugins to define their own command categories
type CustomCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // Unique identifier (e.g., "infrastructure")
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Display name (e.g., "Infrastructure Management")
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Category description
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`      // Display priority (lower = higher priority)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomCategory) Reset() {
	*x = CustomCategory{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomCategory) ProtoMessage() {}

func (x *CustomCategory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomCategory.ProtoReflect.Descriptor instead.
func (*CustomCategory) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *CustomCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomCategory) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// CategoryList contains custom categories defined by a plugin
type CategoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CustomCategory      `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryList) Reset() {
	*x = CategoryList{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryList) ProtoMessage() {}

func (x *CategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryList.ProtoReflect.Descriptor instead.
func (*CategoryList) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *CategoryList) GetCategories() []*CustomCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type StreamMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StreamMessage_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=v1.StreamMessage_Type" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signal        string                 `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	ExitCode      int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,8,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_sdk_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *StreamMessage) GetType() StreamMessage_Type {
	if x != nil {
		return x.Type
	}
	return StreamMessage_STDIN
}

func (x *StreamMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamMessage) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *StreamMessage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *StreamMessage) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *StreamMessage) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StreamMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StreamMessage) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_pkg_plugin_sdk_v1_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_sdk_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/plugin/sdk/v1/plugin.proto\x12\x02v1\"\a\n" +
	"\x05Empty\"\xe6\x03\n" +
	"\x0ePluginMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x17\n" +
	"\amin_sdk\x18\x05 \x01(\tR\x06minSdk\x12&\n" +
	"\x0fbuild_time_unix\x18\x06 \x01(\x03R\rbuildTimeUnix\x12\x1a\n" +
	"\bhomepage\x18\a \x01(\tR\bhomepage\x12\x18\n" +
	"\alicense\x18\b \x01(\tR\alicense\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x123\n" +
	"\x05extra\x18\n" +
	" \x03(\v2\x1d.v1.PluginMetadata.ExtraEntryR\x05extra\x12\x18\n" +
	"\aaliases\x18\v \x03(\tR\aaliases\x12\x1e\n" +
	"\n" +
	"namespaced\x18\f \x01(\bR\n" +
	"namespaced\x128\n" +
	"\fdependencies\x18\r \x03(\v2\x14.v1.PluginDependencyR\fdependencies\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x10PluginDependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\boptional\x18\x03 \x01(\bR\boptional\"\x9b\x02\n" +
	"\vCommandInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\x12 \n" +
	"\vinteractive\x18\x05 \x01(\bR\vinteractive\x12\x16\n" +
	"\x06hidden\x18\x06 \x01(\bR\x06hidden\x12!\n" +
	"\frequires_tty\x18\a \x01(\bR\vrequiresTty\x12#\n" +
	"\rrequires_auth\x18\b \x01(\bR\frequiresAuth\x12\x1e\n" +
	"\n" +
	"visibility\x18\t \x01(\tR\n" +
	"visibility\":\n" +
	"\vCommandList\x12+\n" +
	"\bcommands\x18\x01 \x03(\v2\x0f.v1.CommandInfoR\bcommands\"\x87\x01\n" +
	"\x10ConfigureRequest\x128\n" +
	"\x06config\x18\x01 \x03(\v2 .v1.ConfigureRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc5\x02\n" +
	"\x0eExecuteRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x123\n" +
	"\x05flags\x18\x03 \x03(\v2\x1d.v1.ExecuteRequest.FlagsEntryR\x05flags\x12-\n" +
	"\x03env\x18\x04 \x03(\v2\x1b.v1.ExecuteRequest.EnvEntryR\x03env\x12\x19\n" +
	"\bwork_dir\x18\x05 \x01(\tR\aworkDir\x12\x14\n" +
	"\x05stdin\x18\x06 \x01(\fR\x05stdin\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x02\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\fR\x06stderr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x121\n" +
	"\x14requires_interactive\x18\x06 \x01(\bR\x13requiresInteractive\x124\n" +
	"\x05extra\x18\a \x03(\v2\x1e.v1.ExecuteResponse.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x02\n" +
	"\fCapabilities\x12'\n" +
	"\x0frequires_docker\x18\x01 \x01(\bR\x0erequiresDocker\x12)\n" +
	"\x10requires_network\x18\x02 \x01(\bR\x0frequiresNetwork\x12/\n" +
	"\x13requires_filesystem\x18\x03 \x01(\bR\x12requiresFilesystem\x121\n" +
	"\x14requires_interactive\x18\x04 \x01(\bR\x13requiresInteractive\x12+\n" +
	"\x11required_commands\x18\x05 \x03(\tR\x10requiredCommands\x12%\n" +
	"\x0erequired_paths\x18\x06 \x03(\tR\rrequiredPaths\x12*\n" +
	"\x11required_env_vars\x18\a \x03(\tR\x0frequiredEnvVars\"r\n" +
	"\x0eCustomCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"B\n" +
	"\fCategoryList\x122\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x12.v1.CustomCategoryR\n" +
	"categories\"\xdb\x02\n" +
	"\rStreamMessage\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.v1.StreamMessage.TypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\tR\x06signal\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12%\n" +
	"\x0etimestamp_unix\x18\b \x01(\x03R\rtimestampUnix\"j\n" +
	"\x04Type\x12\t\n" +
	"\x05STDIN\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02\x12\n" +
	"\n" +
	"\x06RESIZE\x10\x03\x12\n" +
	"\n" +
	"\x06SIGNAL\x10\x04\x12\b\n" +
	"\x04EXIT\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06\x12\b\n" +
	"\x04PING\x10\a\x12\b\n" +
	"\x04PONG\x10\b2\xfe\x02\n" +
	"\vGlidePlugin\x12,\n" +
	"\vGetMetadata\x12\t.v1.Empty\x1a\x12.v1.PluginMetadata\x128\n" +
	"\tConfigure\x12\x14.v1.ConfigureRequest\x1a\x15.v1.ConfigureResponse\x12*\n" +
	"\fListCommands\x12\t.v1.Empty\x1a\x0f.v1.CommandList\x129\n" +
	"\x0eExecuteCommand\x12\x12.v1.ExecuteRequest\x1a\x13.v1.ExecuteResponse\x12<\n" +
	"\x10StartInteractive\x12\x11.v1.StreamMessage\x1a\x11.v1.StreamMessage(\x010\x01\x12.\n" +
	"\x0fGetCapabilities\x12\t.v1.Empty\x1a\x10.v1.Capabilities\x122\n" +
	"\x13GetCustomCategories\x12\t.v1.Empty\x1a\x10.v1.CategoryListB1Z/github.com/ivannovak/glide/v2/pkg/plugin/sdk/v1b\x06proto3"

var (
	file_pkg_plugin_sdk_v1_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_sdk_v1_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_sdk_v1_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_sdk_v1_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_sdk_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_sdk_v1_plugin_proto_rawDesc), len(file_pkg_plugin_sdk_v1_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_sdk_v1_plugin_proto_rawDescData
}

var file_pkg_plugin_sdk_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_plugin_sdk_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_plugin_sdk_v1_plugin_proto_goTypes = []any{
	(StreamMessage_Type)(0),   // 0: v1.StreamMessage.Type
	(*Empty)(nil),             // 1: v1.Empty
	(*PluginMetadata)(nil),    // 2: v1.PluginMetadata
	(*PluginDependency)(nil),  // 3: v1.PluginDependency
	(*CommandInfo)(nil),       // 4: v1.CommandInfo
	(*CommandList)(nil),       // 5: v1.CommandList
	(*ConfigureRequest)(nil),  // 6: v1.ConfigureRequest
	(*ConfigureResponse)(nil), // 7: v1.ConfigureResponse
	(*ExecuteRequest)(nil),    // 8: v1.ExecuteRequest
	(*ExecuteResponse)(nil),   // 9: v1.ExecuteResponse
	(*Capabilities)(nil),      // 10: v1.Capabilities
	(*CustomCategory)(nil),    // 11: v1.CustomCategory
	(*CategoryList)(nil),      // 12: v1.CategoryList
	(*StreamMessage)(nil),     // 13: v1.StreamMessage
	nil,                       // 14: v1.PluginMetadata.ExtraEntry
	nil,                       // 15: v1.ConfigureRequest.ConfigEntry
	nil,                       // 16: v1.ExecuteRequest.FlagsEntry
	nil,                       // 17: v1.ExecuteRequest.EnvEntry
	nil,                       // 18: v1.ExecuteResponse.ExtraEntry
}
var file_pkg_plugin_sdk_v1_plugin_proto_depIdxs = []int32{
	14, // 0: v1.PluginMetadata.extra:type_name -> v1.PluginMetadata.ExtraEntry
	3,  // 1: v1.PluginMetadata.dependencies:type_name -> v1.PluginDependency
	4,  // 2: v1.CommandList.commands:type_name -> v1.CommandInfo
	15, // 3: v1.ConfigureRequest.config:type_name -> v1.ConfigureRequest.ConfigEntry
	16, // 4: v1.ExecuteRequest.flags:type_name -> v1.ExecuteRequest.FlagsEntry
	17, // 5: v1.ExecuteRequest.env:type_name -> v1.ExecuteRequest.EnvEntry
	18, // 6: v1.ExecuteResponse.extra:type_name -> v1.ExecuteResponse.ExtraEntry
	11, // 7: v1.CategoryList.categories:type_name -> v1.CustomCategory
	0,  // 8: v1.StreamMessage.type:type_name -> v1.StreamMessage.Type
	1,  // 9: v1.GlidePlugin.GetMetadata:input_type -> v1.Empty
	6,  // 10: v1.GlidePlugin.Configure:input_type -> v1.ConfigureRequest
	1,  // 11: v1.GlidePlugin.ListCommands:input_type -> v1.Empty
	8,  // 12: v1.GlidePlugin.ExecuteCommand:input_type -> v1.ExecuteRequest
	13, // 13: v1.GlidePlugin.StartInteractive:input_type -> v1.StreamMessage
	1,  // 14: v1.GlidePlugin.GetCapabilities:input_type -> v1.Empty
	1,  // 15: v1.GlidePlugin.GetCustomCategories:input_type -> v1.Empty
	2,  // 16: v1.GlidePlugin.GetMetadata:output_type -> v1.PluginMetadata
	7,  // 17: v1.GlidePlugin.Configure:output_type -> v1.ConfigureResponse
	5,  // 18: v1.GlidePlugin.ListCommands:output_type -> v1.CommandList
	9,  // 19: v1.GlidePlugin.ExecuteCommand:output_type -> v1.ExecuteResponse
	13, // 20: v1.GlidePlugin.StartInteractive:output_type -> v1.StreamMessage
	10, // 21: v1.GlidePlugin.GetCapabilities:output_type -> v1.Capabilities
	12, // 22: v1.GlidePlugin.GetCustomCategories:output_type -> v1.CategoryList
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_plugin_sdk_v1_plugin_proto_init() }
func file_pkg_plugin_sdk_v1_plugin_proto_init() {
	if File_pkg_plugin_sdk_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_sdk_v1_plugin_proto_rawDesc), len(file_pkg_plugin_sdk_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_sdk_v1_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_sdk_v1_plugin_proto_depIdxs,
		EnumInfos:         file_pkg_plugin_sdk_v1_plugin_proto_enumTypes,
		MessageInfos:      file_pkg_plugin_sdk_v1_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_sdk_v1_plugin_proto = out.File
	file_pkg_plugin_sdk_v1_plugin_proto_goTypes = nil
	file_pkg_plugin_sdk_v1_plugin_proto_depIdxs = nil
}
