// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/plugin/sdk/v1/plugin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GlidePlugin_GetMetadata_FullMethodName         = "/v1.GlidePlugin/GetMetadata"
	GlidePlugin_Configure_FullMethodName           = "/v1.GlidePlugin/Configure"
	GlidePlugin_ListCommands_FullMethodName        = "/v1.GlidePlugin/ListCommands"
	GlidePlugin_ExecuteCommand_FullMethodName      = "/v1.GlidePlugin/ExecuteCommand"
	GlidePlugin_StartInteractive_FullMethodName    = "/v1.GlidePlugin/StartInteractive"
	GlidePlugin_GetCapabilities_FullMethodName     = "/v1.GlidePlugin/GetCapabilities"
	GlidePlugin_GetCustomCategories_FullMethodName = "/v1.GlidePlugin/GetCustomCategories"
)

// GlidePluginClient is the client API for GlidePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GlidePlugin service defines the RPC interface for plugins
type GlidePluginClient interface {
	// Get plugin metadata
	GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginMetadata, error)
	// Configure the plugin
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// List available commands
	ListCommands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandList, error)
	// Execute a non-interactive command
	ExecuteCommand(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Start an interactive session
	StartInteractive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error)
	// Get required capabilities
	GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error)
	// Get custom categories defined by this plugin
	GetCustomCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategoryList, error)
}

type glidePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewGlidePluginClient(cc grpc.ClientConnInterface) GlidePluginClient {
	return &glidePluginClient{cc}
}

func (c *glidePluginClient) GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginMetadata)
	err := c.cc.Invoke(ctx, GlidePlugin_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glidePluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, GlidePlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glidePluginClient) ListCommands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandList)
	err := c.cc.Invoke(ctx, GlidePlugin_ListCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glidePluginClient) ExecuteCommand(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, GlidePlugin_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glidePluginClient) StartInteractive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GlidePlugin_ServiceDesc.Streams[0], GlidePlugin_StartInteractive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GlidePlugin_StartInteractiveClient = grpc.BidiStreamingClient[StreamMessage, StreamMessage]

func (c *glidePluginClient) GetCapabilities(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Capabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capabilities)
	err := c.cc.Invoke(ctx, GlidePlugin_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *glidePluginClient) GetCustomCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CategoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryList)
	err := c.cc.Invoke(ctx, GlidePlugin_GetCustomCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlidePluginServer is the server API for GlidePlugin service.
// All implementations must embed UnimplementedGlidePluginServer
// for forward compatibility.
//
// GlidePlugin service defines the RPC interface for plugins
type GlidePluginServer interface {
	// Get plugin metadata
	GetMetadata(context.Context, *Empty) (*PluginMetadata, error)
	// Configure the plugin
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// List available commands
	ListCommands(context.Context, *Empty) (*CommandList, error)
	// Execute a non-interactive command
	ExecuteCommand(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Start an interactive session
	StartInteractive(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error
	// Get required capabilities
	GetCapabilities(context.Context, *Empty) (*Capabilities, error)
	// Get custom categories defined by this plugin
	GetCustomCategories(context.Context, *Empty) (*CategoryList, error)
	mustEmbedUnimplementedGlidePluginServer()
}

// UnimplementedGlidePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGlidePluginServer struct{}

func (UnimplementedGlidePluginServer) GetMetadata(context.Context, *Empty) (*PluginMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedGlidePluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedGlidePluginServer) ListCommands(context.Context, *Empty) (*CommandList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommands not implemented")
}
func (UnimplementedGlidePluginServer) ExecuteCommand(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedGlidePluginServer) StartInteractive(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StartInteractive not implemented")
}
func (UnimplementedGlidePluginServer) GetCapabilities(context.Context, *Empty) (*Capabilities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedGlidePluginServer) GetCustomCategories(context.Context, *Empty) (*CategoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomCategories not implemented")
}
func (UnimplementedGlidePluginServer) mustEmbedUnimplementedGlidePluginServer() {}
func (UnimplementedGlidePluginServer) testEmbeddedByValue()                     {}

// UnsafeGlidePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlidePluginServer will
// result in compilation errors.
type UnsafeGlidePluginServer interface {
	mustEmbedUnimplementedGlidePluginServer()
}

func RegisterGlidePluginServer(s grpc.ServiceRegistrar, srv GlidePluginServer) {
	// If the following call pancis, it indicates UnimplementedGlidePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GlidePlugin_ServiceDesc, srv)
}

func _GlidePlugin_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlidePluginServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlidePlugin_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlidePluginServer).GetMetadata(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlidePlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlidePluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlidePlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlidePluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlidePlugin_ListCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlidePluginServer).ListCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlidePlugin_ListCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlidePluginServer).ListCommands(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlidePlugin_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlidePluginServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlidePlugin_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlidePluginServer).ExecuteCommand(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlidePlugin_StartInteractive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GlidePluginServer).StartInteractive(&grpc.GenericServerStream[StreamMessage, StreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GlidePlugin_StartInteractiveServer = grpc.BidiStreamingServer[StreamMessage, StreamMessage]

func _GlidePlugin_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlidePluginServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlidePlugin_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlidePluginServer).GetCapabilities(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlidePlugin_GetCustomCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlidePluginServer).GetCustomCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlidePlugin_GetCustomCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlidePluginServer).GetCustomCategories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GlidePlugin_ServiceDesc is the grpc.ServiceDesc for GlidePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GlidePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GlidePlugin",
	HandlerType: (*GlidePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _GlidePlugin_GetMetadata_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _GlidePlugin_Configure_Handler,
		},
		{
			MethodName: "ListCommands",
			Handler:    _GlidePlugin_ListCommands_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _GlidePlugin_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _GlidePlugin_GetCapabilities_Handler,
		},
		{
			MethodName: "GetCustomCategories",
			Handler:    _GlidePlugin_GetCustomCategories_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartInteractive",
			Handler:       _GlidePlugin_StartInteractive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/plugin/sdk/v1/plugin.proto",
}
